apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-tests-dotnet-basic-fcyywifa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/e2e-tests-dotnet-basic-fcyywifa:azure-d79d9320abee75b1429a3301e5f1dd539f0e4c03
          name: container-image
